### ISSUE TITLE
Add support for badge output type

### ISSUE THREAD

**Issue by marcoceppi** [ublue-os/image-scanner-md#1]
Currently, ublue-scanner supports cli and md output. These work well but as ublue evolves we'll need to add additional output types. This enhancement aims to add a `badge` output which would emulate docker hub and artifacthub style displays:

<img width="958" alt="Screenshot 2023-03-13 at 10 16 11 AM" src="https://user-images.githubusercontent.com/70613/224728173-9a400926-25b7-43f5-af02-7a3d3e70df8b.png">

<img width="1017" alt="Screenshot 2023-03-13 at 10 17 21 AM" src="https://user-images.githubusercontent.com/70613/224728425-4153b95e-6269-4791-bcaf-4c9d7ece57d3.png">

For this, we'll need to process package labels as well as output either pure HTML or a markdown friendly / renderable output that produces a similar experience

**Comment by castrojo** [comment]
Additionally it'd be nice to include an ISO link on each one, which will have a matching github release in the repo for each image. (We don't have this today obviously but just mentioning it now while it's top of mind)
